---
- name: php repository gpg key (bookworm only)
  become: yes
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: raspbian_version.stdout == 'bookworm'

- name: php repository (bookworm only)
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ bookworm main
    filename: php8.list
    state: present
  when: raspbian_version.stdout == 'bookworm'

- name: install php (bookworm)
  become: yes
  apt:
    update_cache: no
    state: present
    name:
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-sqlite3
      - php8.2-intl
  when: raspbian_version.stdout == 'bookworm'

- name: install composer
  become: yes
  apt:
    update_cache: no
    state: present
    name: composer

- name: add current user to www-data group
  become: yes
  user:
    name: "{{ target_user }}"
    groups: www-data
    append: yes

- name: web directory
  become: yes
  file:
    path: "{{ web_home }}"
    state: directory
    owner: "{{ target_user }}"
    group: www-data
    mode: 0775

- name: config directory
  become: yes
  file:
    path: "{{ web_home }}/Config"
    state: directory
    owner: "{{ target_user }}"
    group: www-data
    mode: 0775

- name: public directory
  become: yes
  file:
    path: "{{ web_home }}/public"
    state: directory
    owner: "{{ target_user }}"
    group: www-data
    mode: 0775

- name: Fetch system timezone
  command: timedatectl show --property=Timezone --value
  register: system_timezone

- name: php config file
  become: yes
  template:
    src: Config.php.j2
    dest: "{{ web_home }}/Config/Config.php"
    owner: "{{ target_user }}"
    group: www-data
    mode: 0644

- name: update user's home folder permissions
  become: yes
  file:
    path: "/{{ target_user }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: update srv directory ownership
  become: yes
  file:
    path: "/srv"
    owner: "{{ target_user }}"
    group: www-data
    mode: 0755

- name: update images directory group
  become: yes
  file:
    path: "{{ images_output }}"
    state: directory
    group: www-data

- name: update thumbnails directory group
  become: yes
  file:
    path: "{{ images_output }}/thumb"
    state: directory
    group: www-data

- name: update videos directory group
  become: yes
  file:
    path: "{{ videos_output }}"
    state: directory
    group: www-data

- name: update database folder permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db"
    group: www-data
    mode: 0770

- name: update database file permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db/panel.db"
    group: www-data
    mode: 0770

- name: www-data sudoers atrm as superuser
  become: yes
  copy:
    src: 020_www-data-atrm-nopasswd
    dest: /etc/sudoers.d/020_www-data-atrm-nopasswd
    owner: root
    group: root
    mode: 0440

...
